---
title: ""
output: 
  html_document:
    toc: true
    toc_float: true
---

Education
--------------------------------------------------------------------------------

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td>Columbia University Mailman School of Public Health</td>
    <td style="text-align: right;">Expected May 2026</td>
  </tr>
</table>

Master of Science in Biostatistics with a concentration in Public Health Data Science  

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td>University of California, Los Angeles</td>
    <td style="text-align: right;">June 2024</td>
  </tr>
</table>

Bachelor of Science in Applied Mathematics + Minor in Statistics and Data Science

Professional Experience
--------------------------------------------------------------------------------

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td>Student Research Worker</td>
    <td style="text-align: right;">October 2024 - Present</td>
  </tr>
</table>

Columbia University School of Nursing | New York, NY

- Statistical reviews of data sets and analysis 

- Data cleaning, preparation, and building statistical models in R

- Managing data, assisting with literature reviews, grant, manuscript, and presentation preparation

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td>Sciences Libraries Student Supervisor </td>
    <td style="text-align: right;">January 2022 - June 2024</td>
  </tr>
</table>

UCLA Louise M. Darling Biomedical Library | Los Angeles, CA

- Responsible for ensuring coworkers are on task, assisting with peer-to-peer training, and covering shifts at UCLA Science and Engineering Library, and UCLA Geology Library

- Guiding patrons in research projects through the library search and various medical/scientific databases

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> Well-Being Services Intern </td>
    <td style="text-align: right;"> June 2023 - August 2023</td>
  </tr>
</table>

Beach Cities Health District | Redondo Beach, CA 

- Worked on program evaluations for Workplace Wellness programs at Beach Cities Health District, Redondo Beach Unified School District, and Manhattan Beach Unified School District

- Worked on pedestrian and bicycle crash data to compile a report to send to city council to highlight the issues of safety

- Attended community events focused on maintaining connections and bettering mental health 

Research
--------------------------------------------------------------------------------

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> Directed Reading Program </td>
    <td style="text-align: right;"> April 2023 - June 2023</td>
  </tr>
</table>

UCLA Mathematics Department | Los Angeles, CA

- Used principles of network science to model the spread of disease and how different public health interventions impact the spread of the disease in Python

- Presented research at DRP Colloquium 

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> UCLA Public Health Scholars Training Program </td>
    <td style="text-align: right;"> June 2023 - August 2023</td>
  </tr>
</table>

UCLA Fielding School of Public Health | Los Angeles, CA

- Examined the effects of Valley Fever on farmworkers in California through the social ecological model, a comprehensive literature review, and creation of a poster 

- Presented at the Centers for Disease Control and Prevention in Atlanta, Georgia

Professional Development
--------------------------------------------------------------------------------

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> UCLA Public Health Scholars Training Program </td>
    <td style="text-align: right;"> June 2023 - August 2023</td>
  </tr>
</table>

UCLA Fielding School of Public Health | Los Angeles, CA 

- Attend structured programming to build public health knowledge, develop professional skills, and learn about professional and educational opportunities

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> 11th Annual Workshop to Increase Diversity in Mathematical Modeling and Public Health </td>
    <td style="text-align: right;"> March 2023</td>
  </tr>
</table>

Harvard T.H. Chan School of Public Health | Boston, MA

- A three day conference focusing on several different aspects of mathematical modeling and public health including epidemiological methods and machine learning

- Networked with public health professionals from various schools, including Harvard, Boston University, Massachusetts Institute of Technology

Leadership Experience
--------------------------------------------------------------------------------

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> Outreach Committee Director  </td>
    <td style="text-align: right;"> May 2023 - June 2024</td>
  </tr>
</table>

Advocating Intersectional Medicine | Los Angeles, CA

- Facilitate workshops, presentations, and partnerships with internal UCLA-affiliated organizations and external organizations to further educate AIM members and the community at large about overarching issues relating to medicine and public health. 

- Facilitates workflow, communication, and keeps track of active membership within the Outreach committee.
Work with the Social Media committee to collaborate with other UCLA clubs and organizations. 

<table style="width: 100%; font-weight: bold;">
  <tr>
    <td> Student Staff CHR Supervisory Principles Summer Workshopr  </td>
    <td style="text-align: right;"> August 2022</td>
  </tr>
</table>

- Learned about conflict mediation, 6 principles of persuasion, leadership styles, and how to become a better leader. 


Skills
--------------------------------------------------------------------------------
**Mathematics:** Differential Equations, Mathematical Modeling, Mathematical Statistics and Probability, Statistical Modeling, Network Science, Mathematical Cryptology, Computational Statistics, Data Science, Biostatistical Methods

**Coding:** Python (Basic to Intermediate), R (Intermediate), C++ (Basic)

**Research:** Navigating various databases, literature reviews

**Technology:** Proficiency in Microsoft and Google Suite Applications






You can go [home](index.html)

