---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("ny_noaa")

noaa_df <- 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  
  mutate(tmax, tmax = as.integer(tmax) / 10) %>% 
  mutate(tmin, tmin = as.integer(tmin)/ 10) %>%  
  mutate(prcp, pcrp = as.integer(prcp)/ 10)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Minimum Temperature by Month

```{r}
noaa_df %>% 
  mutate(month = as.factor(month)) %>% 
  plot_ly(x = ~month, y = ~tmin, type = "box")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Average Precipitation by Month

```{r}
noaa_df %>% group_by(month) %>% 
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) %>% plot_ly(x = ~month, y = ~avg_prcp, type = "scatter", mode = "line") 
```

### Average Maximum Temperature by Year

```{r}
noaa_df %>% 
  plot_ly() %>% 
  add_histogram(x = ~tmax, name = "Max Temperature", opacity = 0.6) %>% 
  add_histogram(x = ~tmin, name = "Min Temperature", opacity = 0.6) %>% 
    layout(
         title = "Distribution of Maximum and Minimum Temperature",
         xaxis = list(title = "Temperature in Celsius"),
         yaxis = list(title = "Frequency"))
  
```



