---
title: "Plotly and Dashboards"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

library(p8105.datasets)

library(plotly)
```


# Plots 

Making interactive plots in Plotly

```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2) %>% 
  select(rating, neighbourhood_group, neighbourhood, room_type, lat, long, price) %>% 
  drop_na(rating) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt", 
    price %in% 100:500
  )
```

Using Plotly

**Scatterplot**
```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: ", price, "\nNeigborhood: ", neighbourhood)) %>% 
  plot_ly(
    x = ~lat, 
    y = ~long, 
    color = ~price, 
    type = "scatter", 
    mode = "markers", 
    alpha = 0.5, 
    text = ~text_label
  )
```


**Boxplot**

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(x = ~neighbourhood, y = ~ price, color = ~neighbourhood, type = "box")
```


**Bar Chart**

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
```

**Heat Maps**

```{r}
plot_ly(
  z = volcano, 
  type = "heatmap"
)
```

good for covariance matricies

**Cholorpleth**

```{r}
plot_ly(type = "choropleth" , locations = c( "AZ", "CA", "VT" ) , locationmode = "USA-states" , colorscale = "Viridis" , z = c( 10, 20, 40 )) %>% layout( geo = list(scope = "usa" ))
```

